"""initial schema

Revision ID: a2db012f0629
Revises: 
Create Date: 2026-05-19 05:46:42.274677

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2db012f0629'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('premium_expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_usage',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_usage_user_date', 'api_usage', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_id'), 'api_usage', ['id'], unique=False)
    op.create_table('conversion_history',
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversion_history_id'), 'conversion_history', ['id'], unique=False)
    op.create_index(op.f('ix_conversion_history_title'), 'conversion_history', ['title'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversion_history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_favorite_created', 'favorites', ['created_at'], unique=False)
    op.create_index('idx_favorite_user_conversion', 'favorites', ['user_id', 'conversion_id'], unique=True)
    op.create_index(op.f('ix_favorites_id'), 'favorites', ['id'], unique=False)
    op.create_table('line_mappings',
    sa.Column('conversion_id', sa.Integer(), nullable=False),
    sa.Column('line_text', sa.Text(), nullable=False),
    sa.Column('casual_katakana', sa.Text(), nullable=False),
    sa.Column('formal_katakana', sa.Text(), nullable=False),
    sa.Column('line_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversion_id'], ['conversion_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_line_mapping_conversion', 'line_mappings', ['conversion_id', 'line_order'], unique=False)
    op.create_index(op.f('ix_line_mappings_id'), 'line_mappings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_mappings_id'), table_name='line_mappings')
    op.drop_index('idx_line_mapping_conversion', table_name='line_mappings')
    op.drop_table('line_mappings')
    op.drop_index(op.f('ix_favorites_id'), table_name='favorites')
    op.drop_index('idx_favorite_user_conversion', table_name='favorites')
    op.drop_index('idx_favorite_created', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_conversion_history_title'), table_name='conversion_history')
    op.drop_index(op.f('ix_conversion_history_id'), table_name='conversion_history')
    op.drop_table('conversion_history')
    op.drop_index(op.f('ix_api_usage_id'), table_name='api_usage')
    op.drop_index('idx_api_usage_user_date', table_name='api_usage')
    op.drop_table('api_usage')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
